targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: "Cubit$|Interactor$|Mapper$"
          file_name_pattern: "_cubit$|_interactor$|_mapper$"
