name: e_wallet
description: EWallet. The project must help people organize their spending.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui helpers
  cupertino_icons: 1.0.5
  flutter_svg: 2.0.7
  flutter_native_splash: 2.3.1
  animated_text_kit: 4.2.2
  flex_color_scheme: 7.3.1
  rive: 0.12.3
  # use for local fonts only
  google_fonts: 5.1.0

  #state management
  flutter_bloc: 8.1.3
  bloc_effects: 1.0.3
  provider: 6.0.5

  # using to avoid stateful widgets
  flutter_hooks: ^0.20.1

  #data classes replacement
  freezed: 2.4.1
  freezed_annotation: 2.4.1

  #di
  get_it: 7.6.0
  injectable: 2.3.0

  #firebase services
  firebase_core: 2.15.1
  firebase_auth: 4.8.0
  firebase_database: 10.2.5
  firebase_crashlytics: 3.3.5

  #local storage
  shared_preferences: 2.2.0

  #navigation
  go_router: 10.1.2
  navigator:
    path: modules/navigator

  #log helper
  logging: 1.2.0
  logging_interceptor:
    path: modules/logging_interceptor

  #dart extensions
  collection: 1.18.0

  #tests
  mockito: 5.4.2
  bloc_test: 9.1.4
  golden_toolkit: 0.15.0
  device_preview: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #localization
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  #lints
  flutter_lints: 2.0.3

  # TODO: replace it or buy licence
  dart_code_metrics: 5.7.6

  #code generation
  injectable_generator: 2.4.0
  build_runner: 2.4.6
  assets_gen: 1.5.0

  #launch icon
  flutter_launcher_icons: 0.13.1

# dart code metrics conflicts with google fonts.
dependency_overrides:
  http: 1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/
   - assets/google_fonts/
   - assets/animations/