name: e_wallet
description: EWallet. The project must help people organize their spending.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui helpers
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  animated_text_kit: ^4.2.2
  google_fonts: ^5.1.0

  #state management
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

  #data classes replacement
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

  #di
  get_it: ^7.2.0
  injectable: ^2.1.2

  #firebase services
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_database: ^10.2.4
  firebase_crashlytics: ^3.3.4

  #local storage
  shared_preferences: ^2.2.0

  #navigation
  go_router: ^10.0.0

  #log helper
  logging: ^1.2.0

  #dart extensions
  collection: ^1.17.1

  #tests
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  golden_toolkit: ^0.15.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  #lints
  flutter_lints: ^2.0.0

  #code generation
  injectable_generator: ^2.1.6
  build_runner: ^2.2.0
  assets_gen: ^1.5.0

  #launch icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/